export const dgData = [
    {
        id: 1,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `Throw Pink Women's Disc Golf Championship`,
        field: `FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0PjUaJ1oklihgy-PijCY1e`,
        thumbnail: `https://i.ytimg.com/vi/ddvXZKeC93o/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCK7CUGGWzoZDFn-yvhsz1u-CUkKQ`,
    },
    {
        id: 2,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `Disc Golf Pro Tour Championship`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1m2mnaTB--LOLP-g5BsasU`,
        thumbnail: `https://i.ytimg.com/vi/Nsmjd1KZP3c/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB26Pp7szSSS_cXaTmWGqNWcpKXOQ`,
    },
    {
        id: 3,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `United States Disc Golf Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2lUW2Q2G_Flgwcp7lJb2he`,
        thumbnail: `https://i.ytimg.com/vi/FWNnqwkDgI8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCqLvaGJAu0MnhEbnv7qqoTk5w2wA`,
    },
    {
        id: 4,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `United States Women's Disc Golf Championship`,
        field: `FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2h1YAvdt1-DyimE8xhRtm9`,
        thumbnail: `https://i.ytimg.com/vi/PyjG9CYjLS8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDrzD13qaRZJ4C6oxSXJPcahh_qoA`,
    },
    {
        id: 5,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `MVP Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1EVOd6O0RzdpOYdJ_ISuyo`,
        thumbnail: `https://i.ytimg.com/vi/mUNIgJIeYjM/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAQoS3_uOYA8MYdftNLYio0L0SqJw`,
    },
    {
        id: 6,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `Professional Disc Golf Association World Championships`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1PbSbSFCpbOLC9CjTfcuL7`,
        thumbnail: `https://i.ytimg.com/vi/TDrRp9bTw1A/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC-mUp7AW3tlSX54AVQnGtbkogZ4g`,
    },
    {
        id: 7,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `Discraft Great Lakes Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA36kel0_jK1dXp-ZqqkKKd4`,
        thumbnail: `https://i.ytimg.com/vi/FRE4phkkbQM/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCIMTq09dhs_uAiZsTtX0FH_VW-ug`,
    },
    {
        id: 8,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `LWS Open at Idlewild`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0lzuU-wFnmSrq8r__FrS42`,
        thumbnail: `https://i.ytimg.com/vi/0oc6pjJrHKc/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCHhoNAn8chrv4FVuKq9EQ3TCXVKQ`,
    },
    {
        id: 9,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `Ledgestone Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2Ku0Yv8zmW7stQMJ9DkQqI`,
        thumbnail: `https://i.ytimg.com/vi/vKe0a43E1Po/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDZ2hBiFGyli-5wVST-B9_RXS_NcQ`,
    },
    {
        id: 10,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `European Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2XMHXmY0kVqge1GbEDY7xk`,
        thumbnail: `https://i.ytimg.com/vi/quPnPr3abSI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBtAg06W4CXt-l1yQ1SvTtUhkIzNA`,
    },
    {
        id: 11,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `PCS Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA09wTDtoTFV2h2ize91N_YH`,
        thumbnail: `https://i.ytimg.com/vi/NfPHb8hjqHY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD3DvelGCNOZTs5CREK0BcphGVxcQ`,
    },
    {
        id: 12,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `The Preserve Championship`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2UDI7sBfIv9wkKcAh1-q9_`,
        thumbnail: `https://i.ytimg.com/vi/ZdsGtE1HXTQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDPQWVbW1lmSGMIUKlDVMoyZ68YKw`,
    },
    {
        id: 13,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `PDGA Champions Cup`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2L6TFrb7naNLdQt019C4-O`,
        thumbnail: `https://i.ytimg.com/vi/D_Hm-gqTeJI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB4JWK9kAgSI22P3k4O4NCSNdUVdQ`,
    },
    {
        id: 14,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `Des Moines Challenge`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA16K8IBqpCxCK6ozBz_th3t`,
        thumbnail: `https://i.ytimg.com/vi/bbgmHv0StrM/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBE_aIh8uJqjWs3U4ipT5lEB27S6w`,

    },
    {
        id: 15,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `Dynamic Discs Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1kfeDFjyx6_G635LKlKF-G`,
        thumbnail: `https://i.ytimg.com/vi/2jahOuxZaJk/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDnOmPNTRarByqCvwEQyMf57c_AbA`,
    },
    {
        id: 16,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `Portland Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA32D9asWBIRAZZy4zN--lWy`,
        thumbnail: `https://i.ytimg.com/vi/SpoFlluX7Xw/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC_-lfgBKtlOFu6RpI6TypZKd77uQ`,
    },
    {
        id: 17,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `OTB Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA27pZdPGbKY3SlTeHAmFTiq`,
        thumbnail: `https://i.ytimg.com/vi/JMsT-_KBW1w/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCKF63uk6O4m3CcFIF36Yk11JVZqA`,
    },
    {
        id: 18,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `Jonesboro Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1V4fAPRVG62jtZv2K506pQ`,
        thumbnail: `https://i.ytimg.com/vi/qB1_trMdlnE/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDsfLTdqa7QTNukI18VwxCy7zyRmg`,
    },
    {
        id: 19,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `Music City Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0dIKmgceXiBrAvSSMVqB-k`,
        thumbnail: `https://i.ytimg.com/vi/K8BdTlPo7xQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAPqULIiTXXVnXo0sQrrBJtt_IWmg`,
    },
    {
        id: 20,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `The Open at Austin`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0MD5yAmjRVW7er3iM7n2MP`,
        thumbnail: `https://i.ytimg.com/vi/PnbrPEXXrIY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDLoi1AjEFlILeREmF1iD4_yPDGvg`,
    },
    {
        id: 21,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `WACO Annual Charity Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3fBoqwdehOGWM3D8m2EH0V`,
        thumbnail: `https://i.ytimg.com/vi/Ht5YiECRtn0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCedcSfyUMuOdtIs8KO6GebqhY2hA`,
    },
    {
        id: 22,
        productionCompany: `JomezPro`,
        year: 2023,
        tournament: `Las Vegas Challenge`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0lfsgq0uH218IpxmYP3BHZ`,
        thumbnail: `https://i.ytimg.com/vi/3lAmM_jmLSQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA7D5R1NoMZQp5oBNgg21FNTPVn3Q`,
    },
    {
        id: 23,
        productionCompany: `JomezPro`,
        year: 2022,
        tournament: `Professional Disc Golf Association World Championships`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2xTRhbLae2dHjKzxnPaKnR`,
        thumbnail: `https://i.ytimg.com/vi/IUyBY22wfHk/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD-9Z-Qprincep-Z320xCLJmVDwOg`,
    },
    {
        id: 24,
        productionCompany: `DGPT`,
        year: 2022,
        tournament: `Mid America Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLLys5veYanmVS5zBECCQCdfT6fYG38Q-H`,
        thumbnail: `https://i.ytimg.com/vi/Er1AJNXcgeU/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCMvkkikE55Wr1L4nxE3Js9qyxuVg`,
    },
    {
        id: 25,
        productionCompany: `CCDG`,
        year: 2023,
        tournament: `Beaver State Fling`,
        field: `FPO`,
        link: `https://www.youtube.com/playlist?list=PLbnvbtJ11PvFYLrPe5GAFVd-KleS-Kn1p`,
        thumbnail: `https://i.ytimg.com/vi/7UexbohecxQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDvHmeAqnNGqtYduwjsQxja19tN4A`,
    },
    {
        id: 26,
        productionCompany: `GK Pro`,
        year: 2022,
        tournament: `TruBank Des Moines Challenge`,
        field: `FPO`,
        link: `https://www.youtube.com/playlist?list=PLeyLPtLudZ9WuYu8uMkRhBjOfa_MuYzrP`,
        thumbnail: `https://i.ytimg.com/vi/5WSXXbc7_04/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBkg8qy3Yzv_ZTzTdlnmKr6TQl7Ww`
    },
    {
        id: 27,
        productionCompany: `Gatekeeper Media`,
        year: 2023,
        tournament: `Maine State Championshps`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PL09cidsQGUyyGaCXQ6OuP72gnDr_8q10z`,
        thumbnail: `https://i.ytimg.com/vi/TU-Q0CKuIaA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC-uHTgiwk3-HKsaAiNx2R0cCzG8w`,
    },
    {
        id: 28,
        productionCompany: `Ace Run Pro`,
        year: 2023,
        tournament: `DGMT Finale`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLhqhSm47vaqhrEZjO_uaaMaV_PpT4ZDNO`,
        thumbnail: `https://i.ytimg.com/vi/PLwDDROp2bA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAbw2c9ilvG2VXruMvaYGMOULuXsw`,
    },
    {
        id: 29,
        productionCompany: `The Disc Golf Guy`,
        year: 2023,
        tournament: `Big Arm Challenge`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PL4_t3454p5esM_rN6mbGr-yflLuOlH0Oa`,
        thumbnail: `https://i.ytimg.com/vi/f_p9QqegCYk/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA3xfOR7X7e7buZcCuDah2ycnibhQ`
    },
]