export const dgData = [
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `Throw Pink Women's Disc Golf Championship`,
        field: `FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0PjUaJ1oklihgy-PijCY1e`,
        thumbnail: `https://i.ytimg.com/vi/ddvXZKeC93o/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCK7CUGGWzoZDFn-yvhsz1u-CUkKQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `Disc Golf Pro Tour Championship`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1m2mnaTB--LOLP-g5BsasU`,
        thumbnail: `https://i.ytimg.com/vi/Nsmjd1KZP3c/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB26Pp7szSSS_cXaTmWGqNWcpKXOQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `United States Disc Golf Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2lUW2Q2G_Flgwcp7lJb2he`,
        thumbnail: `https://i.ytimg.com/vi/FWNnqwkDgI8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCqLvaGJAu0MnhEbnv7qqoTk5w2wA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `United States Women's Disc Golf Championship`,
        field: `FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2h1YAvdt1-DyimE8xhRtm9`,
        thumbnail: `https://i.ytimg.com/vi/PyjG9CYjLS8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDrzD13qaRZJ4C6oxSXJPcahh_qoA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `MVP Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1EVOd6O0RzdpOYdJ_ISuyo`,
        thumbnail: `https://i.ytimg.com/vi/mUNIgJIeYjM/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAQoS3_uOYA8MYdftNLYio0L0SqJw`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `Professional Disc Golf Association World Championships`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1PbSbSFCpbOLC9CjTfcuL7`,
        thumbnail: `https://i.ytimg.com/vi/TDrRp9bTw1A/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC-mUp7AW3tlSX54AVQnGtbkogZ4g`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `Discraft Great Lakes Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA36kel0_jK1dXp-ZqqkKKd4`,
        thumbnail: `https://i.ytimg.com/vi/FRE4phkkbQM/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCIMTq09dhs_uAiZsTtX0FH_VW-ug`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `LWS Open at Idlewild`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0lzuU-wFnmSrq8r__FrS42`,
        thumbnail: `https://i.ytimg.com/vi/0oc6pjJrHKc/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCHhoNAn8chrv4FVuKq9EQ3TCXVKQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `Ledgestone Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2Ku0Yv8zmW7stQMJ9DkQqI`,
        thumbnail: `https://i.ytimg.com/vi/vKe0a43E1Po/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDZ2hBiFGyli-5wVST-B9_RXS_NcQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `European Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2XMHXmY0kVqge1GbEDY7xk`,
        thumbnail: `https://i.ytimg.com/vi/quPnPr3abSI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBtAg06W4CXt-l1yQ1SvTtUhkIzNA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `PCS Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA09wTDtoTFV2h2ize91N_YH`,
        thumbnail: `https://i.ytimg.com/vi/NfPHb8hjqHY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD3DvelGCNOZTs5CREK0BcphGVxcQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `The Preserve Championship`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2UDI7sBfIv9wkKcAh1-q9_`,
        thumbnail: `https://i.ytimg.com/vi/ZdsGtE1HXTQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDPQWVbW1lmSGMIUKlDVMoyZ68YKw`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `PDGA Champions Cup`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2L6TFrb7naNLdQt019C4-O`,
        thumbnail: `https://i.ytimg.com/vi/D_Hm-gqTeJI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB4JWK9kAgSI22P3k4O4NCSNdUVdQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `Des Moines Challenge`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA16K8IBqpCxCK6ozBz_th3t`,
        thumbnail: `https://i.ytimg.com/vi/bbgmHv0StrM/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBE_aIh8uJqjWs3U4ipT5lEB27S6w`,

    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `Dynamic Discs Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1kfeDFjyx6_G635LKlKF-G`,
        thumbnail: `https://i.ytimg.com/vi/2jahOuxZaJk/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDnOmPNTRarByqCvwEQyMf57c_AbA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `Portland Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA32D9asWBIRAZZy4zN--lWy`,
        thumbnail: `https://i.ytimg.com/vi/SpoFlluX7Xw/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLC_-lfgBKtlOFu6RpI6TypZKd77uQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `OTB Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA27pZdPGbKY3SlTeHAmFTiq`,
        thumbnail: `https://i.ytimg.com/vi/JMsT-_KBW1w/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCKF63uk6O4m3CcFIF36Yk11JVZqA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `Jonesboro Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1V4fAPRVG62jtZv2K506pQ`,
        thumbnail: `https://i.ytimg.com/vi/qB1_trMdlnE/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDsfLTdqa7QTNukI18VwxCy7zyRmg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `Music City Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0dIKmgceXiBrAvSSMVqB-k`,
        thumbnail: `https://i.ytimg.com/vi/K8BdTlPo7xQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAPqULIiTXXVnXo0sQrrBJtt_IWmg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `The Open at Austin`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0MD5yAmjRVW7er3iM7n2MP`,
        thumbnail: `https://i.ytimg.com/vi/PnbrPEXXrIY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDLoi1AjEFlILeREmF1iD4_yPDGvg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `WACO Annual Charity Open`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3fBoqwdehOGWM3D8m2EH0V`,
        thumbnail: `https://i.ytimg.com/vi/Ht5YiECRtn0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCedcSfyUMuOdtIs8KO6GebqhY2hA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2023,
        tournament: `Las Vegas Challenge`,
        field: `both MPO and FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0lfsgq0uH218IpxmYP3BHZ`,
        thumbnail: `https://i.ytimg.com/vi/3lAmM_jmLSQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA7D5R1NoMZQp5oBNgg21FNTPVn3Q`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `DGPT Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1840WE-NRfZRtBobyH0Xtl`,
        thumbnail: `https://i.ytimg.com/vi/-WjjBrpN3HQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAe2oZLttsRt7KQO6hZhDeavD5mBQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `MVP Open at Maple Hill`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA11ebHjUVxoZ4H-AOQt9dn4`,
        thumbnail: `https://i.ytimg.com/vi/cUv2tOKmxB4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB9AbgtuIF1vTY0Kdjvm1YrCDAb5g`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `Discraft's Green Mountain Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3jQQbNExiUjz9jR0wWmjfP`,
        thumbnail: `https://i.ytimg.com/vi/8oJPuweOI0I/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCXAK0xebadYgcOGSCScmQxE0AGtA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `PDGA Pro World Championships`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2xTRhbLae2dHjKzxnPaKnR`,
        thumbnail: `https://i.ytimg.com/vi/IUyBY22wfHk/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD-9Z-Qprincep-Z320xCLJmVDwOg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `Des Moines Challenge`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3NMmqg6ioqOn1QFOxNu7PV`,
        thumbnail: `https://i.ytimg.com/vi/-YV1MpcNvtk/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBvOQWq3yCAI6jB3wwH7IptXQ7Xyw`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `Discraft Ledgestone Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3U0t5ukzdWXF4vJgbx6DSn`,
        thumbnail: `https://i.ytimg.com/vi/hh2Zs3QzuMw/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB59lQzXmh1F3L_krKp-wKnQi8Ayw`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `Discraft's Great Lakes Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2Mf7pDD3aXF49uo_SQ-ZRG`,
        thumbnail: `https://i.ytimg.com/vi/EkDgVwgzvw8/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAmvx-O4n7LH4JDdeieW1uupzbPwg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `LWS Open at Idlewild`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3TDipHZJy12EJ-CGENuz0d`,
        thumbnail: `https://i.ytimg.com/vi/u26oKtaZQkk/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDIx7dppmmhKjdSRBWmF_j917iPxg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `United States Women's Disc Golf Championship`,
        field: `FPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2AmbrV3AcrHseEkYiUlCwV`,
        thumbnail: `https://i.ytimg.com/vi/Gr3tLVnXx-4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAvyvlHoG0g-Q_DUrz5JYOcN9C6jQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `The Preserve Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0aWBEU2ZcyD1NeqKipFevI`,
        thumbnail: `https://i.ytimg.com/vi/uKxq0l5eiy4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBPwxXXyGKsh9OP36PANbohT69_bg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `Portland Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1kmMVSoiOz2nCb9YP1K9ul`,
        thumbnail: `https://i.ytimg.com/vi/lhQ9xb6oCrI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCkzaUKztnifC2ufPjGwP2GTchC8w`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `OTB Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2gG4Wg1TaxzX95TDeLK9xL`,
        thumbnail: `https://i.ytimg.com/vi/sdOxwN0dbZA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBgxJU_5qVP1Zj09Z7i0PsffRGmEA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `Dynamic Discs Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3znAuWSDzcqmytSW42jx_n`,
        thumbnail: `https://i.ytimg.com/vi/EdK4yyHXrKU/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCjZ5Ah7hzioNBvKeuxGbE5rYwuYA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `Jonesboro Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1KMdVKMKQu40ZcpXiydyoz`,
        thumbnail: `https://i.ytimg.com/vi/2OldFaNalX0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBiUednsehyCxghbUoJgbvKpfAagQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `PDGA Champions Cup`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3wR0DKqESH0XxBpefjZbc4`,
        thumbnail: `https://i.ytimg.com/vi/qoKLTE8aSIM/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLA3h5fadOQdSH2NzC-Pb4MSKiJ49w`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `Texas State Disc Golf Championships`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3D4iS3DMUbPCKNfs0jyDcZ`,
        thumbnail: `https://i.ytimg.com/vi/Cd77p-v3vhc/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDh1rcYPt-CJQPX3L3P7wNe4C3Fgg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `Waco Annual Charity Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1wKu6C7k98V5Z_3ksZd5pZ`,
        thumbnail: `https://i.ytimg.com/vi/cwt4u0O5IvA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBEZ7k16N_m4_ayk0y6eZhRGFDhwQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2022,
        tournament: `Las Vegas Challenge`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2c8AZHZf6oA46i47I1h-xG`,
        thumbnail: `https://i.ytimg.com/vi/UzkmklPZiQE/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBSa7w1Xsj0m_ajQk8KW5c2uqZZvw`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `NADGT Championships`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA20fmsG9tu2K6M1uBS5EVNN`,
        thumbnail: `https://i.ytimg.com/vi/q9qNijkLB9Y/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBQg5Z6eARL39CHn8o0SO5R8Vrfzw`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Resistance Discs Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3tTyDrUlJ-4mhzfqO0mpVP`,
        thumbnail: `https://i.ytimg.com/vi/FTjEBa3Pzuw/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBtzQgo5FtF9OvdVM52Hq4p9gsKoQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `DGPT Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0MNFYFgyEf5UO3vLfT8QjI`,
        thumbnail: `https://i.ytimg.com/vi/G0o1V_kVukg/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCCuFfArfRhoTi5XTRLkxKCqjHV0Q`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Music City Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2YWu0Ban5XVkJckczQ5geX`,
        thumbnail: `https://i.ytimg.com/vi/SB2BVmn6uog/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBQ6T6uNvYOWAIwWEnogTcYetloSQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Green Mountain Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA33HzNP7TFEmI-8AdYETOEW`,
        thumbnail: `https://i.ytimg.com/vi/p_NCXAYgAlA/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLApoUIns8IomT7Byf3R2GfnBSRYTw`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `MVP Open at Maple Hill`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2jgl54jeVfM2Sjf5AhJGT5`,
        thumbnail: `https://i.ytimg.com/vi/jR-scJXxSbI/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCilQ5YnDNzoda3rqPRSU3Q2CnGFQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Delaware Disc Golf Challenge`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0s1CzYN7Fu0-IYcsSUXoA_`,
        thumbnail: `https://i.ytimg.com/vi/icJ3v0EG5zQ/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAzlu0vRmY3q7eoZ-Oxgd4nC-EQKA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Idlewild Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3zPHEK2L78YZth6_eJOK_O`,
        thumbnail: `https://i.ytimg.com/vi/jl7lvCXzIAU/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCZT1cGKPcmVFj8ZCegqBgcFEibHQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Ledgestone Insurance Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA07VaKhWQ9mNGtAGBeAlp2N`,
        thumbnail: `https://i.ytimg.com/vi/lD9JPjDYxx0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBxmFpV2fSAYoUCDze99aaiRERciA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `The Preserve Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1escjw83LW_eJPGTbu0Q4h`,
        thumbnail: `https://i.ytimg.com/vi/Os3-WgY_8m0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCjzEt5U7didpq7gDKZVZ3WAK3usA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Discraft Great Lakes Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0D-_ZS1K3Fa9EGOLKsAc-g`,
        thumbnail: `https://i.ytimg.com/vi/AM1__vBUv-Q/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD4n6sA9RI89U9yXBdcSN4cxUiFqQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `PDGA Pro World Championships`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0MJnzlpzb3EAY6W8NXDgqc`,
        thumbnail: `https://i.ytimg.com/vi/b-OICF4pyK4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLByPI99JulAhsOA3U_biZZACP3DFQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Portland Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2hMzhz5-DGM2kfPzJIsNoW`,
        thumbnail: `https://i.ytimg.com/vi/cxTwKMn26UM/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCMShqkUmflZRtN58YVf4LgS31P8Q`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Santa Cruz Masters Cup`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3ixBHmw2EKURouIyKN3AKY`,
        thumbnail: `https://i.ytimg.com/vi/3D9F4RYijuU/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDyDjvPLjpHvIS6lKPnR80ul5zDtg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `OTB Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0SjKFOqguY_FNug8oWOqz_`,
        thumbnail: `https://i.ytimg.com/vi/Gp5ORpL9frU/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCEyji9Qat-YdylLtbpzjJlUGNY-A`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Dynamic Discs Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2I_rxyL8GD4leANZ7kzeaW`,
        thumbnail: `https://i.ytimg.com/vi/jUxrD34MdPs/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDI7NN4i7hrYTA--wG9TnQLYU87xg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Jonesboro Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1l1QEQxX8eHWsDXxQBG6c1`,
        thumbnail: `https://i.ytimg.com/vi/pll82nODOd0/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDz6k3BAI86lzoCGK3XcTFjyqK-dg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Texas State Disc Golf Championships`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1Ntfg7aTFVkgv3r8eYvMVl`,
        thumbnail: `https://i.ytimg.com/vi/udibX3G4Nto/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAl5_vnU7zrg1DBZH8BGDqnbIP-8w`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Waco Annual Charity Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0jY-wLy-32V0vHvV5K0KpO`,
        thumbnail: `https://i.ytimg.com/vi/wgHT7HeXP08/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAzy-Dle2OPqZityWeBbxd4rforcw`,
    },
    {
        productionCompany: `Jomez`,
        year: 2021,
        tournament: `Las Vegas Challenge`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2ytUHFVb1oV40fO4-VJgVv`,
        thumbnail: `https://i.ytimg.com/vi/WFwUfe9IA8o/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDqH3LEdhIOZSLu26RafJ3xDCsxDA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2020,
        tournament: `DGPT Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA21oNTvB7h1w5Kc0rIh3qrD`,
        thumbnail: `https://i.ytimg.com/vi/QyiljcDSAkY/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLAWLkljVXSniqqOc1PAyw3kZoDS-A`,
    },
    {
        productionCompany: `Jomez`,
        year: 2020,
        tournament: `Jonesboro Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA236qRiKDcKJ9bYBHcriFd4`,
        thumbnail: `https://i.ytimg.com/vi/towazx5pr34/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLD8kWOuJpRsp3CSMpW1OWJIcniehA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2020,
        tournament: `MVP Open at Maple Hill`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2ofrTzhcwz44tg7IFma3Rn`,
        thumbnail: `https://i.ytimg.com/vi/iAtQ4LgXaZ4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBjlAMz6WZyUuooJIbbgR9_JqEgQA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2020,
        tournament: `Green Mountain Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA3NzuxmIuHboS2W_03Ne2X3`,
        thumbnail: `https://i.ytimg.com/vi/gKIQq-R3Jl4/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLABxa_0H6IAFaQnnl1hVip1mzFNDg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2020,
        tournament: `Dynamic Discs Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2r4tW5EQ9Cw1IL-l1TrPhX`,
        thumbnail: `https://i.ytimg.com/vi/Dc-xNJKHDdw/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDi_C4GjR6W2921C-vEnfj08SYIVA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2020,
        tournament: `Discraft Ledgestone Insurance Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2x8WBAg-ImPZqihLkc_862`,
        thumbnail: `https://i.ytimg.com/vi/Yvg2D0UdfUs/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLBos-Gfq4C91wlLqnycPhjSydGXRQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2020,
        tournament: `Idlewild Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1Y1hFuZhQgcvqYsKI98jOk`,
        thumbnail: `https://i.ytimg.com/vi/ubXnq1dgMSM/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDxo98C6SYxSjZgNvdJJRpHsUZBDA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2020,
        tournament: `Discraft Great Lakes Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA0C2t6JhoR2ls3Sf3C7nJOA`,
        thumbnail: `https://i.ytimg.com/vi/cKYA98DYPWc/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDYwToOQzd6qSvXBl25R3jbwUmyLg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2020,
        tournament: `Preserve Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA27fjDkSFmEDveY2nWBQSbL`,
        thumbnail: `https://i.ytimg.com/vi/HZwC4slm22s/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLCOrERIfwPxNgjhJCaR1y7C0pjXdg`,
    },
    {
        productionCompany: `Jomez`,
        year: 2020,
        tournament: `Waco Annual Charity Open`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA1bn0i--glBIYzGGh2qRFrN`,
        thumbnail: `https://i.ytimg.com/vi/d1uUFJQaWac/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLDBVtspHNXVMbqS94cXvejulkXFDA`,
    },
    {
        productionCompany: `Jomez`,
        year: 2020,
        tournament: `Memorial Championship`,
        field: `MPO`,
        link: `https://www.youtube.com/playlist?list=PLZ1LrAadOyA2DKexGwKB3lO2UoIijlZNa`,
        thumbnail: `https://i.ytimg.com/vi/eia65NGrkYE/hqdefault.jpg?sqp=-oaymwEXCNACELwBSFryq4qpAwkIARUAAIhCGAE=&rs=AOn4CLB-Ec-S160BGBP_gJrgr3Z9n8kuSQ`,
    },
    {
        productionCompany: `Jomez`,
        year: 2019,
        tournament: `Placeholder`,
        field: `MPO`,
        link: ``,
        thumbnail: ``,
    },

]